
"""empty message

Revision ID: 9b3ac6be109e
Revises: 35f29b1701bd
Create Date: 2019-08-04 21:12:04.289453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3ac6be109e'
down_revision = '35f29b1701bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiler_function_arguments',
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('schema_id', sa.Integer(), nullable=False),
    sa.Column('function_id', sa.Integer(), nullable=False),
    sa.Column('arg_id', sa.Integer(), nullable=False),
    sa.Column('is_null', sa.Integer(), nullable=False),
    sa.Column('is_expression', sa.Integer(), nullable=False),
    sa.Column('use_default', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('server_id', 'database_id', 'schema_id', 'function_id', 'arg_id')
    )
    op.create_table('saved_reports',
    sa.Column('rid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('direct', sa.Boolean(), nullable=False),
    sa.Column('dbname', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('rid')
    )
    # ### end Alembic commands ###


def downgrade():
    pass

    # ### end Alembic commands ###
